version: "3.9"

services:



  hello-agent:
    image: hello-agent:0.1.0
    labels:
      - "agent.enabled=true"
      - "agent.port=8000"
    expose: ["8000"]

  gateway:
    build: ./gateway
    ports: ["8080:8080"]
    depends_on: [hello-agent]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro   # read-only socket

